### ISSUE TITLE
Compilation failure - Cannot find module axios[Bug]: 

### ISSUE THREAD

**Issue by jaydubb12** [vuestorefront/shopify#101]
### Expected Behavior

Compilation will be successful on initial run

### Actual Behavior

Compilation fails due to missing dependencies.

1. Middleware compilation fails, cannot find @vue-storefront/shopify-api/server
2. Theme package fails, cannot find "axios"
3. Theme package fails, cannot find "@vue-storefront/core which is required by files in the packages/theme/composables directory

### Possible Solution

1. @vue-storefront/shopify-api as a dependency to the theme package
2. Add axios as a dependency to the theme package
3. Add @vue-storefront/core as a devDependency to the theme package

### Steps to reproduce

Build theme package for v1.06

### What version of shopify integration are you using?

1.06

### What version of Node.js are you using?

16.13.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevensilvers** [comment]
@jaydubb12  have you run the workspaces to install everything /shopify has those dependencies included that is the composoables. Assuming you just straight on build theme package without building the required dependencies which coming from composables and api-client.
