### ISSUE TITLE
More configurable | verbose rollup configuration [Feature]: 

### ISSUE THREAD

**Issue by jaydubb12** [vuestorefront/shopify#105]
### How the project can be improved?

Provide developers incremental tools that will proactively ....

- Provide them warning messages generated during the build
- Provide them detailed insights if / when a circular dependency is detected
- Provide a progress element that will allow the develop to view that the build is progressing, and which allows for improved debugging to validate what is being processed
- Provide the build process the ability to augment the build output with nodePolyfills 
- Provide the build process the ability to utilize core-js polyfills and babel transpiling as part of build process
- Provide developers ability to utilize typescript transformations as part of the build process
- Provide developers a visual output  of the typecoverage once the build completes
- Provide developers the ability to view the type coverage within a browser

### What are the acceptance criteria?

- Ability for a developer to be able to set specific configurations based on the output format specified within rollup
- Ability for a developer to view the progress of the rollup build
- Ability for a developer to have access to effective debugging tools and console messages as part of the rollup build

### Additional information

- The current setup is a "minimal configuration" approach, which is not necessarily bad, but I feel the added feature will make the overall build process and related developer activities more useful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffp-0** [comment]
Isn't the vite config more insightful to move instead of this? Let me know what you think?
