### ISSUE TITLE
[Bug]: UI looks different than other integrations

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/shopify#113]
### Expected Behavior
UI should be consistent for all integrations similarly to Commercetools and other integrations https://demo-ct.vuestorefront.io/

### Actual Behavior
UI is different than in other integrations. It can be caused by the old version of Storefront UI, custom components or anything else. It was observed after creating project from shopify-template

![image](https://user-images.githubusercontent.com/37120330/143212660-574906e8-ddc7-4226-819c-45661dcd7410.png)

![image](https://user-images.githubusercontent.com/37120330/143212722-dc0a9c7d-c3ff-441d-81c0-2845f4973b8d.png)

![Uploading image.png…]()

### Possible Solution
 It can be caused by the old version of Storefront UI, custom components or anything else. It was observed after creating project from shopify-template

### Steps to reproduce
Generate project from vsf-init and choose shopify template.

### What version of shopify integration are you using?
2.3.3

### What version of Node.js are you using?
14.0.0

### What browser (and version) are you using?
chrome

### What operating system (and version) are you using?
macOS

### Code of Conduct
* [x] I agree to follow this project's Code of Conduct

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SH-3) by [Unito](https://www.unito.io)

**Comment by jeffpdotone** [comment]
The fixes we're already merged to develop branch and we'll still need to implement forgot password and other function that is missing to make a next release.
