### ISSUE TITLE
[Bug]: yarn start will cause FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by tingxin** [vuestorefront/shopify#131]
### Expected Behavior

i run it by :
sudo yarn start --max_old_space_size=3096

### Actual Behavior

in 2 or 3 hours, it will be killed by follow issue
<--- Last few GCs --->

[8537:0x4dfe310] 44483799 ms: Mark-sweep (reduce) 1944.7 (2005.5) -> 1943.9 (2006.0) MB, 3499.1 / 0.1 ms  (average mu = 0.285, current mu = 0.005) allocation failure scavenge might not succeed
[8537:0x4dfe310] 44487316 ms: Mark-sweep (reduce) 1945.0 (2006.0) -> 1944.2 (2006.5) MB, 3158.1 / 0.1 ms  (average mu = 0.205, current mu = 0.102) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb02ec0 node::Abort() [/usr/bin/node]
 2: 0xa181fb node::FatalError(char const*, char const*) [/usr/bin/node]
 3: 0xced88e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xcedc07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xea5ea5  [/usr/bin/node]
 6: 0xeb557d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 7: 0xeb827e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
 8: 0xe793e2 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]
 9: 0xe73d0c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]
10: 0xe8913a v8::internal::Handle<v8::internal::PropertyArray> v8::internal::Factory::CopyArrayAndGrow<v8::internal::PropertyArray>(v8::internal::Handle<v8::internal::PropertyArray>, int, v8::internal::AllocationType) [/usr/bin/node]
11: 0x1083af5 v8::internal::JSObject::MigrateToMap(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Map>, int) [/usr/bin/node]
12: 0x10a5581 v8::internal::LookupIterator::ApplyTransitionToDataProperty(v8::internal::Handle<v8::internal::JSReceiver>) [/usr/bin/node]
13: 0x10c4e0b v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin) [/usr/bin/node]
14: 0x107b721 v8::internal::JSObject::CreateDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::Maybe<v8::internal::ShouldThrow>) [/usr/bin/node]
15: 0x1084423 v8::internal::JSReceiver::SetOrCopyDataProperties(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertiesEnumerationMode, v8::base::ScopedVector<v8::internal::Handle<v8::internal::Object> > const*, bool) [/usr/bin/node]
16: 0x11ffc5b v8::internal::Runtime_CopyDataProperties(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
17: 0x15e7879  [/usr/bin/node]
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ec2-user@ip-172-31-31-70 shopify]$
[ec2-user@ip-172-31-31-70 shopify]$ 

### What version of shopify integration are you using?

main branch

### What version of Node.js are you using?

v16.13.0

### What browser (and version) are you using?

96.0.4664.55

### What operating system (and version) are you using?

linux  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpdotone** [comment]
Is increasing more size old space doesn't do any good?

**Comment by jeffpdotone** [comment]
Closing this as there are no further updates. Thank you.
