### ISSUE TITLE
Filters can't implement due to no API available 

### ISSUE THREAD

**Issue by aureate-labs-team** [vuestorefront/shopify#20]
## What is the motivation for adding / enhancing this feature?
implement available filters from facets. However, need Shopify API to implement it. Right now, no API available for filters. 

## What are the acceptance criteria 

Display available filters at PLP and make it functional to filter the products list
- [ ] ...

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by pablogiralt** [comment]
Hi, I believe [filtering by tags is possible](https://community.shopify.com/c/Shopify-APIs-SDKs/Storefront-API-filtering-on-product-variant-color/m-p/567702).  Filters in VSF could be implemented using tags and the Shopify store manager would have to add tags to represent product attributes like color, size, etc manually, or [use an app](https://apps.shopify.com/smart-tags) to maintain this automatically

Another option would be to use a filtering app like [the one from Boost ](https://boostcommerce.net/) which [has an api](https://help.boostcommerce.net/article/458-filter-search-api)

I know this are not ideal solutions and that it would be much better that shopify implements filtering by variant options and metafields in its api, but this might not be happening anytime soon.

Im really looking forward to VSF supporting Shopify and will for sure use your integration in future projects. Thanks for the awesome work @aureate-labs-team

**Comment by aureate-labs-team** [comment]
@pablogiralt Thanks for your inputs. For now, we are thinking to manage filters manually using graphQL global queries. Will keep the repo updated with our latest changes. So please be in loop :)
