### ISSUE TITLE
Mobile bottom bar: display mobile menu

### ISSUE THREAD

**Issue by mricci-dkskfDJD** [vuestorefront/shopify#233]
### How the project can be improved?

Clicking on the menu section inside the mobile bottom bar doesn't do anything.

In the demo there is a menu with this options:
- CLOTHES]
- EVENT DRESSING
- ACCESSORIES
- And so on

It appears that from mobile there's no way to navigate to those sections

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpdotone** [comment]
Fixed by #278
