### ISSUE TITLE
Can't show Size and Color 

### ISSUE THREAD

**Issue by Ayap1pp1** [vuestorefront/shopify#240]
### What is your question / Please describe your issue

Hi, I could show my Shopify products and categories on demo application: https://shopify-pwa.aureatelabs.com/, but I cannot manage to show sizes and colors. It seems like the site can count how many variation of sizes I have. However, all texts are missing.  When I use inspector on google web browser I see the value of sizes is empty and I guess they cannot wrriten as String? I have English and Swedish as acceptLanguage in middleware.config.js. How can I solve this problem? I found out that some links to documents are missing. For example, on this page, the link to Internationaliztion is missing: https://docs.vuestorefront.io/shopify/guide/configuration.html#nuxt-shopify-configuration. Is there something I missed becuase of the missing document? 

![Screenshot 2022-03-01 101834](https://user-images.githubusercontent.com/48164437/156140797-169fd728-8218-4a4e-8191-2dcf9323c78e.png)
![Screenshot 2022-03-01 101928](https://user-images.githubusercontent.com/48164437/156141162-678bbe47-9bef-467c-a388-90e8180e8485.png)
![Screenshot 2022-03-01 102031](https://user-images.githubusercontent.com/48164437/156141247-e5bc8f58-f5ce-49b6-a789-8d1dd8a1fde6.png)

### What version of shopify integration are you using?

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aureate-labs-team** [comment]
Removing **.value** from the attributes in the product.vue file will help you :)
