### ISSUE TITLE
Questions relates to VueStorefront/Shopify

### ISSUE THREAD

**Issue by E0han** [vuestorefront/shopify#27]
Hey there,

Sorry if this is the wrong place to ask questions. I'm impressed by the work you did so far. May I ask if I'm looking to use the Api client and composables packages for my customised UI theme, how do I process to embed them into my codebase? I understand it's a WIP project, just trying to play around with it, and see is there anything I can help to build.

Thanks

**Comment by E0han** [comment]
and may I ask is this project protected by any license?

**Comment by aureate-labs-team** [comment]
Thanks for reaching out to us. If I'm not getting wrong, by customized UI theme, means a NUXT theme? If so, you can simply start from theme/nuxt.config.js. Please refer to "_https://github.com/vuestorefront/shopify/blob/master/packages/theme/nuxt.config.js_"

for more details, you can ping us on slack ([#help](https://vuestorefront.slack.com/archives/CA68P1JUF)) Thanks
