### ISSUE TITLE
[Feature]: Forgot Password is an empty file?

### ISSUE THREAD

**Issue by mricci-dkskfDJD** [vuestorefront/shopify#270]
### How the project can be improved?

The reset password page is empty, looks like the reset password is missing.
https://github.com/vuestorefront/shopify/blob/main/packages/theme/pages/ResetPassword.vue

Is it something related to a specific integration? Maybe it is different beetwen Shopify, Magento, ... ?

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpdotone** [comment]
Fixed and closed by #335
