### ISSUE TITLE
[Bug]: SignUp VSF error with Shopify integration

### ISSUE THREAD

**Issue by Andrieddu** [vuestorefront/shopify#324]
### Expected Behavior

During SignUp if would type an email that already exist should trow an error such as "This email exist already"

### Actual Behavior

While I try to sign up a email that exist already instaed of giving me a "normal error" from Shopify such as "This email exist already" or something like that, it just give me a VSF error.

[VSF][error]: useUser/register TypeError: Cannot read properties of undefined (reading 'customerUserErrors')

### Steps to reproduce

Just try to SignUp with a email that already exist.

### What version of shopify integration are you using?

1.1.0 (Shopify)

### What version of Node.js are you using?

16.13.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

Ubuntu 21.10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aureate-labs-team** [comment]
Will be resolved with new release
