### ISSUE TITLE
Deploying to SSR configuration - help required

### ISSUE THREAD

**Issue by rrubio** [vuestorefront/shopify#385]
### Provide a description of requested docs changes

Hi Guys,

I'm able to run the application locally by using "yarn dev".

When trying to deploy to firebase using SSR but not having much luck. I've added "server-middleware" folder and "middleware.config.js". Though i'm not sure if this is correct, there isn't much documentation on this process.

I've previously deployed to firebase using the same method (plain nuxtjs project), however, it appears i'm missing something for vuestorefront. Any tips are much appreciated.

This is the example i followed for a previous project which worked - https://medium.com/@sirofjelly/deploying-a-nuxt-ssr-server-side-rendering-app-to-google-firebase-5d90117167db

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rrubio** [comment]
It appears that the issue is on the build itself. Another error that popped up was around "@glidejs/glide" not able to import, i got this working by adding it to nuxt.config file on transpile.

However, i'm now getting other errors see below (This must be called within a setup function). The error is consistent across node 14.21.1 and 16.16.0. Any tips would be much appreciated.

Glidejs error fixed by adding to transpile under "nuxt.config" file - 

![Screenshot 2023-04-30 at 5 32 29 pm](https://user-images.githubusercontent.com/4221574/235341544-96015fd1-8f92-4f74-8a6e-81809c389882.png)


This error occurs when using "yarn dev" and "yarn start" -

![Screenshot 2023-04-30 at 5 32 11 pm](https://user-images.githubusercontent.com/4221574/235341546-eb3124e3-a5be-49ad-ab00-4a478c4a2d7b.png)

**Comment by skirianov** [comment]
Hi @rrubio 👋 

Vue Storefront does not support firebase as a hosting platform, due to the nature of the Firebase architecture. 
Vue Storefront application comes with 2 appications - Nuxt and Middleware and Middleware should always run, though Firebase does not have this functionality.

Please take a look at Digital Ocean, Heroku or any other providers like AWS Lightsail

**Comment by rrubio** [comment]
Thank you @skirianov. Ended up using google cloud run.
