### ISSUE TITLE
Can't generate static site

### ISSUE THREAD

**Issue by quickshiftin** [vuestorefront/shopify#50]
I've got the basic integration working with sample data loaded in Shopify, but when I try running `yarn generate` there are a lot of errors, and the static site is missing many pages and sections.

Note, the site seems to work fine when running as `yarn dev`.

example error messages from `yarn generate`.

```
ERROR  [VSF][error] useCart/load connect ECONNREFUSED 127.0.0.1:80                                                     14:46:00

  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) (repeated 3 times)


 ERROR  [VSF][error] useProduct/relatedProducts/search connect ECONNREFUSED 127.0.0.1:80                                14:46:00

  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

I've opened up all the permissions for the Shopify private app too.

**Comment by quickshiftin** [comment]
It looks like for the generator to work, you have to have `yarn start` running in a separate shell, is that correct? It seemed to work that way... How then could we control where the generator is looking, because my original `nuxt.config.js` had this:
```
  server: {
    port: 3001,
    host: '0.0.0.0'
  },
```
Changing it to
```
  server: {
    port: 80,
    host: '127.0.0.1'
  },
```
then running `yarn start` in a separate shell before running `yarn generate` worked...

**Comment by quickshiftin** [comment]
I've discovered from the Discord VSF channel, static generation is not supported at this time.

**Comment by oscarmanderj** [comment]
I would suggest deploying on vercel using their ssr cache. It achieves a
similar result.

This is what we did on bareblends.com.au
