### ISSUE TITLE
[Bug]: Cart Session cookie not cleared on successful checkout

### ISSUE THREAD

**Issue by razza12** [vuestorefront/shopify#63]
### Expected Behavior

If returning to frontend site after successful checkout - the old cart should be cleared and a new cart created

### Actual Behavior

The old cart is pulled based on the session cookie - and users are unable to add items to the cart or checkout until the session cookie is cleared

### What version of shopify integration are you using?

Newest

### What version of Node.js are you using?

Newest

### What browser (and version) are you using?

Firefox

### What operating system (and version) are you using?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aureate-labs-team** [comment]
Please upgrade your template files to the latest ones
