### ISSUE TITLE
Compilation error - v1.06 [Bug]: 

### ISSUE THREAD

**Issue by jaydubb12** [vuestorefront/shopify#93]
### Expected Behavior

Build process would complete without errors

### Actual Behavior

Compilation of theme module results in the following error
```
 FATAL  The "id" argument must be of type string. Received type boolean (false)                                                               10:43:20

  at new NodeError (node:internal/errors:329:5)
  at validateString (node:internal/validators:129:11)
  at Module.require (node:internal/modules/cjs/loader:989:3)
  at require (node:internal/modules/cjs/helpers:92:18)
  at useRawSource (node_modules/@vue-storefront/nuxt/lib/modules/raw-sources-loader.js:8:17)
  at node_modules/@vue-storefront/nuxt/lib/modules/raw-sources-loader.js:20:79
  at Array.map (<anonymous>)
  at ModuleContainer.VueStorefrontPerformanceModule (node_modules/@vue-storefront/nuxt/lib/modules/raw-sources-loader.js:20:64)
  at ModuleContainer.VueStorefrontNuxtModule (node_modules/@vue-storefront/nuxt/lib/module.js:90:20)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)
```

### Possible Solution

The issue appears to trace back to the custom plugin from Vue-Storefront via this file ```packages/theme/node_modules/@vue-storefront/nuxt/lib/modules/raw-sources-loader.js```. I was able to resolve the issue by commenting line 20, which is seeking to populate an option specific to the environment.  Candidly, I am not a fan of how VSF is doing this, and am proposing a change to some of these files via that repository.  

Here is the revised file, with line 20 commented
```
const log = require('../helpers/log');
const isProduction = require('../helpers/isProduction');
const resolveDependency = require('../helpers/resolveDependency');

module.exports = function VueStorefrontPerformanceModule (options) {
  const useRawSource = (packageName) => {
    const pkgPath = resolveDependency(`${packageName}/package.json`);
    const pkg = require(pkgPath);

    if (pkg.module) {
      this.extendBuild(config => {
        config.resolve.alias[pkg.name + '$'] = resolveDependency(`${packageName}/${pkg.module}`);
      });
    }

    this.options.build.transpile.push(packageName);
    log.info(`Using raw source/ESM for ${pkg.name}`);
  };

 //options.useRawSource[isProduction(options) ? 'prod' : 'dev'].map(package => useRawSource(package));
};

```

### Steps to reproduce

1. Fork project / current release
2. Run commands to build api-client, then composables
3. Run command ```yarn dev:theme```
4. Console will display error

### What version of shopify integration are you using?

1.0.6

### What version of Node.js are you using?

v16.13.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

MacOS

### Relevant log output

```shell
See error description above, includes console output
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevensilvers** [comment]
Hi, @jaydubb12 unable to replicate the issue mentioned above. Did you already try yarn install with clear cache?

**Comment by jaydubb12** [comment]
@sevensilvers I did try again with the yarn cache cleared, and the referenced line uncommented, and it worked. 

Will call it a magic fix for now :).
