### ISSUE TITLE
cjs / es conflict "cannot import outside of a module"[Bug]: 

### ISSUE THREAD

**Issue by jaydubb12** [vuestorefront/shopify#95]
### Expected Behavior

Compilation and startup of front end would be completed without error

### Actual Behavior

Startup of project results in error ""cannot import outside of a module"

This is caused by the fact that the storefront-ui package is NOT built and given that cjs cannot utilize the import statement from legacy EMCA

### Possible Solution

Add the module "storefront-ui" to the transpile option under the build configuration in the ```nuxt.js``` file

Resulting code will look like this 

```build: {
    transpile: ['vee-validate/dist/rules', 'storefront-ui'],
    plugins: [
      new webpack.DefinePlugin({
        'process.VERSION': JSON.stringify({
          // eslint-disable-next-line global-require
          version: version0.version,
          lastCommit: process.env.LAST_COMMIT || ''
        })
      })
    ],
```

Alternative Solution####
Attempt to utilize the import as a nuxt module approach, which was recently published. Have not tried this yet personally, but is a viable option

### Steps to reproduce

Attempt to run command ```yarn dev:theme``` and note vue strart up issue

### What version of shopify integration are you using?

1.06

### What version of Node.js are you using?

16.13.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

MacOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sevensilvers** [comment]
Hi, @jaydubb12 thanks for the report. But could we follow where are you experiencing these bugs as it is deemed not replicable to my machine? Thanks
